// This file was auto-generated by ML.NET Model Builder. 

using System;
using TgaProductML.Model;

namespace TgaProductML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Metin = @"evet anlatıldığı gibi",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Durum with predicted Durum from sample data...\n\n");
            Console.WriteLine($"Metin: {sampleData.Metin}");
            Console.WriteLine($"\n\nPredicted Durum value {predictionResult.Prediction} \nPredicted Durum scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
