// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace TgaProductML.Model
{
    public class ModelInput
    {
        [ColumnName("Metin"), LoadColumn(0)]
        public string Metin { get; set; }


        [ColumnName("Durum"), LoadColumn(1)]
        public string Durum { get; set; }


    }
}
